---
- name: Deploy PostgreSQL with Patroni
  hosts: my_mts_hosts
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: 
          - postgresql
          - postgresql-contrib
          - python3-pip
          - python3-dev
          - libpq-dev
          - python3-venv
        state: present

    - name: Install Patroni
      pip:
        name: patroni[etcd]
        executable: pip3

    - name: Configure PostgreSQL
      template:
        src: postgresql.conf.j2
        dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '0644'
      notify: Restart PostgreSQL

    - name: Start PostgreSQL
      systemd:
        name: postgresql
        enabled: yes
        state: started

    - name: Initialize Patroni
      command: patronictl -c /etc/patroni.yml initdb
      args:
        creates: /var/lib/postgresql/{{ postgresql_version }}/main/PG_VERSION
      notify: Start Patroni

  handlers:
    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    - name: Start Patroni
      systemd:
        name: patroni
        state: started 
